INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("FL-0748","pfrancol@unjbg.edu.pe","Dr. Pablo Franco Leon");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("MG-0602","cmendozag@unjbg.edu.pe","Dra. Cecilia Mendoza Gómez");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("CC-0547","pchambic@unjbg.edu.pe","Dr. Pedro Pablo Chambi Condori");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("AB-2499","ralvarezb@unjbg.edu.pe","Dra. Rina María Alvarez Becerra");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("RG-3438","maria.reinafarje@upch.pe","Mg. Maria Reinafarje Gonzales");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("CC-5380","yovanacarpio2020@gmail.com","Dra. Yovana Marilu Carpio Choque");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("MP-4859","ruben_marquez_921@hotmail.com","Mg. Ruben Leoncio Marquez Pinto");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("HQ-3400","jherreraq@gmail.com","Dr. José Alfredo Herrera Quispe");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("FC-3453","juanfloresc61@hotmail.com","Mg. Juan Salomon Flores Carcahusto");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("CM-4475","delmar.cml@gmail.com","Mg. Delma Carrasco Molina");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("CG-3474","acanales7@hotmail.com","Dr. Angel Canales Gutierrez");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("PP-2227","apachecop@unjbg.edu.pe","Dr. Alberto Pacheco Pacheco");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("LJ-5205","ricardo.linares@pucp.edu.pe","MSc. Ricardo José Linares Juarez");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("CU-0063","ncalderonu@unjbg.edu.pe","Dr. Nicolas Fidel Calderon Urriola");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("VC-5423","raulvargas@unap.edu.pe","Dr. Raul Vargas Castillo");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("MC-4916","pmontalvoc@unjbg.edu.pe","Dra. Patricia Verónica Montalvo Chavez");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("AG-0061","banyosag@unjbg.edu.pe","Dr. Bartolome Anyosa Gutierrez");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("FA-3721","francoapd@yahoo.es","Dr. Pedro Franco Apaza");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("ED-2928","mescobedod@unjbg.edu.pe","Mg. Moisés Ismael Escobedo Dueñas");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("RM-3352","irodriguezm@unjbg.edu.pe","Mg. Isabel Rodriguez Monzon");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("MS-0425","indesur2007@gmail.com","Dr. Ricardo Mendoza Salas");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("SP-2221","tsotop@unjbg.edu.pe","Dr. Tolomeo Raúl Soto Perez");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("VM-4766","vanivemol_20@hotmail.com","Dr. Jehovanni Fabricio Velarde Molina");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("DOEP-203","vanivemol_20@hotmail.com","Dr. Samuel Perez Quispe");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("VP-4430","angel.vega@unjbg.edu.pe","Mg. Angel Grover Vega Pilco");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("BV-0603","sbazanv@unjbg.edu.pe","Dra. Silvia Bazan Velasquez");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("MMC-5377","sobeyda.mazuelos@gmail.com","MSc. Zobeyda Madelayde Mazuelos Chavez");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("RC-0068","cesarrivasplata@yahoo.com","MSc. Cesar Rivasplata Cabanillas");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("RQ-5045","retoquintanilla@gmail.com","Mg. Angel Fabian Reto Quintanilla");
INSERT INTO DOCENTE(CODIGO, CORREO, NOMBRE) VALUES("YP-5195","renzoyp1@yahoo.com","Dr. Renzo Yufra Peralta");

-- DELETE FROM DOCENTE WHERE ID != null