INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (1, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (2, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (3, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (4, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (5, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (6, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (7, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (8, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (9, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (10, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (11, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (12, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (13, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (14, 3);
INSERT INTO PROGRAMA_APERTURADO(PROGRAMA, PROCESO) VALUES (15, 3);

SELECT P.NOMBRE AS PROGRAMA, PC.NOMBRE AS PROCESO FROM programa_aperturado PA JOIN PROGRAMA P JOIN PROCESO PC ON PA.PROGRAMA = P.ID AND PA.PROCESO = PC.ID;
