INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Salud Pública", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Gerencia y administración de la educación", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Tecnología Educativa", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Proyectos de Inversión", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Ciencias con Mencion en Gestión Ambiental y Desarrollo Sostenible", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Ingeniería De Sistemas e Informática - Administración de Tecnologías de Información", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Gerencia Pública", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Gestión Empresarial", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Derecho con Mención en Derecho Penal y Procesal Penal", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Ciencias con Mencion en Contabilidad: Auditoría", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Derecho Civil y Comercial", 0);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Administración", 1);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Ciencias Ambientales", 1);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Ciencias de la Educación", 1);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Epidemiología", 1);
INSERT INTO PROGRAMA (NOMBRE, TIPO) VALUES ("Ciencias Contables y Financieras", 1);